name: npm test
on:
  workflow_dispatch:
jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-node-version
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: npm-action-install
        run: npm install
  job-two:
    needs: job-one
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-node-version
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: npm-action-test
        run: npm test
