
name: interact2
on: 
  pull_request:
  workflow_dispatch:

jobs:
  create-issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - id: short_sha
        run: |          
          echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      #- id: short_sha
      #  run: |
      #   echo "GITHUB_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV 
      #   USE {{env.GITHUB_SHA}} in next step
      - name: Create issue using REST API
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{"title":"Found a bug","body":"I'\''m having a problem with this.","labels":["bug"]}'

